# Generated by Django 3.0 on 2019-06-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mega',
            name='register1',
        ),
    ]
