# Generated by Django 3.0 on 2019-06-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_remove_mega_register1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formal',
            name='register1',
        ),
        migrations.RemoveField(
            model_name='informal',
            name='register1',
        ),
    ]
