# Generated by Django 3.0 on 2019-06-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_auto_20190615_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('Event_name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('Phone_no', models.CharField(max_length=120, verbose_name='Phone no')),
            ],
        ),
    ]
